version: '3'

volumes:
  pg_data_production:
  static_volume:
  media:


services:
  db_kitty:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: alinemr/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/app/media/cats/images
    depends_on:
      - db_kitty

  frontend:
    image: alinemr/kittygram_frontend  
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: alinemr/kittygram_gateway  
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media:/app/media/cats/images
    ports:
      - 9000:80