# docker-compose.production.yml
version: '3'

volumes:
  pg_data_production:
  static_volume:
  media:

# Всё отличие — заменяем build на image и указываем, какой образ использовать
services:
  db_kitty:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: alinemr/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/media
  frontend:
    image: alinemr/kittygram_frontend  # Качаем с Docker Hub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: alinemr/kittygram_gateway  # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/media
    ports:
      - 9000:80